# Generated by Django 4.1.6 on 2024-01-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0004_location_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
