# Generated by Django 4.1.6 on 2024-01-11 21:19

from django.db import migrations, models
import lendloop.models.ranking


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0006_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.FloatField(validators=[lendloop.models.ranking.non_negative_validator])),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Rankings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='rankings',
            field=models.ManyToManyField(blank=True, related_name='products', to='lendloop.ranking'),
        ),
    ]
