# Generated by Django 4.1.6 on 2024-01-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0007_ranking_product_rankings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
