# Generated by Django 4.1.6 on 2024-01-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0008_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
