# Generated by Django 4.1.6 on 2024-01-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0009_alter_status_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_status', to='lendloop.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_status', to='lendloop.status')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ManyToManyField(through='lendloop.ProductStatus', to='lendloop.status'),
        ),
        migrations.AddField(
            model_name='status',
            name='products',
            field=models.ManyToManyField(related_name='products_for_status', through='lendloop.ProductStatus', to='lendloop.status'),
        ),
    ]
