# Generated by Django 4.1.6 on 2024-01-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0010_productstatus_product_status_status_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatus',
            options={'verbose_name_plural': "Product's status"},
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('categories', models.ManyToManyField(to='lendloop.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
    ]
