# Generated by Django 4.1.6 on 2024-01-13 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lendloop', '0012_productstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 14, 26, 28, 563506)),
        ),
    ]
