# Generated by Django 4.1.6 on 2024-01-14 20:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lendloop', '0014_alter_product_user_alter_productstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 21, 36, 1, 693553)),
        ),
    ]
