# Generated by Django 4.1.6 on 2024-01-14 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0016_alter_productstatus_date_alter_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 21, 49, 32, 344389)),
        ),
    ]
