# Generated by Django 4.1.6 on 2024-01-14 22:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lendloop', '0017_remove_status_user_alter_productstatus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 1, 14, 23, 24, 43, 644304))),
            ],
            options={
                'verbose_name_plural': "Product's rent",
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_rent', models.BooleanField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Rents',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='rent',
            name='product',
            field=models.ManyToManyField(related_name='products_for_rent', through='lendloop.ProductRent', to='lendloop.product'),
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_rent', to='lendloop.product'),
        ),
        migrations.AddField(
            model_name='productrent',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_rent', to='lendloop.rent'),
        ),
        migrations.AddField(
            model_name='product',
            name='rent',
            field=models.ManyToManyField(related_name='rent', through='lendloop.ProductRent', to='lendloop.rent'),
        ),
    ]
