# Generated by Django 4.1.6 on 2024-01-14 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0018_productrent_rent_remove_status_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='products',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='date_to',
        ),
        migrations.AlterField(
            model_name='productrent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 23, 45, 6, 479239)),
        ),
        migrations.DeleteModel(
            name='ProductStatus',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
