# Generated by Django 4.1.6 on 2024-01-16 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0019_remove_status_products_remove_rent_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 18, 21, 25, 368628)),
        ),
    ]
