# Generated by Django 4.1.6 on 2024-01-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0020_alter_productrent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrent',
            name='date',
        ),
    ]
