# Generated by Django 4.1.6 on 2024-01-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0021_remove_productrent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_product', to='lendloop.product'),
        ),
        migrations.AlterField(
            model_name='productrent',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_product', to='lendloop.rent'),
        ),
    ]
