# Generated by Django 4.1.6 on 2024-01-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0022_alter_productrent_product_alter_productrent_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='in_rent',
        ),
    ]
