# Generated by Django 4.1.6 on 2024-01-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0023_remove_rent_in_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rent',
        ),
        migrations.DeleteModel(
            name='ProductRent',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
