# Generated by Django 4.1.6 on 2024-01-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0025_remove_availability_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='lendloop.product'),
        ),
    ]
