# Generated by Django 4.1.6 on 2024-01-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0030_orderproduct_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='availabilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lendloop.availability'),
        ),
    ]
