# Generated by Django 4.1.6 on 2024-01-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0031_remove_availability_product_product_availabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availabilities',
        ),
    ]
