# Generated by Django 4.1.6 on 2024-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0032_remove_product_availabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabilities',
            field=models.ManyToManyField(blank=True, related_name='products', to='lendloop.availability'),
        ),
    ]
