# Generated by Django 4.1.6 on 2024-01-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0033_product_availabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availabilities',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
