# Generated by Django 4.1.6 on 2024-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0035_product_date_from_product_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_to',
            field=models.DateField(),
        ),
    ]
