# Generated by Django 4.1.6 on 2024-02-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0037_remove_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='insurance',
        ),
    ]
