# Generated by Django 4.1.6 on 2024-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0038_remove_orderproduct_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
