# Generated by Django 4.1.6 on 2024-02-10 13:45

from django.db import migrations, models
import django.db.models.deletion
import lendloop.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0039_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.FloatField(validators=[lendloop.models.review.non_negative_validator])),
                ('comment', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lendloop.order')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
