# Generated by Django 4.1.6 on 2024-02-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendloop', '0041_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
    ]
